### ISSUE TITLE
Huge binary size in dev profile

### ISSUE THREAD

**Issue by LucasJavaudin** [pola-rs/polars#12486]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

`src/main.rs`
```rust
use polars::prelude::*;

fn main() {
    let s = Series::new("a", [1, 2, 3, 4, 5]);
    println!("{}", s);
}
```

`Cargo.toml`
```toml
[package]
name = "polars-test"
version = "0.1.0"
edition = "2021"

[dependencies]
"polars" = { version = "0.34.2", default-features = false }
```

Build dev binary with `cargo build`.

### Issue description

When compiling a rust binary with polars code, I end up with very large binary file, for the dev profile.

With the example shown above, I get a filesize of 691 MB (vs 22 MB with release profile).

When I strip the binary of the symbols ([using `strip=true`](https://doc.rust-lang.org/cargo/reference/profiles.html#strip)), the problem disappears as I get a filesize of 30 MB (vs 9.2 MB with release profile).

I have the same problem in more complex situations. For the program I am working on, the binary size increases from ~170 MB to ~1.3 GB when I add polars as a dependency.

### Expected behavior

For the example below, the binary size should be around 30 MB.

### Installed versions

<details>

</details>
