### ISSUE TITLE
RollingExpr Not Found During Complie

### ISSUE THREAD

**Issue by ngriffiths13** [pola-rs/polars#12592]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```toml
[dependencies]
pyo3 = {version = "0.20.0", features = ["extension-module"]}
pyo3-polars = {version = "0.9.0", features = ["derive"]}
polars = {version = "0.35.4", features = ["fmt", "performant", "chunked_ids", "lazy", "zip_with", "random"]}
faer = {version = "0.14.1", features = ["ndarray"]}
ndarray = "0.15.6"
numpy = "0.20.0"
serde = {version = "1.0.190", features=["derive"]}
hashbrown = "0.14.2"
```

### Issue description

When compiling the crates above, I receive the following error:
```
error[E0599]: no variant named `RollingExpr` found for enum `dsl::function_expr::FunctionExpr`
   --> /Users/nelsongriffiths/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.35.4/src/logical_plan/optimizer/cse_expr.rs:329:71
    |
329 |                 function: FunctionExpr::Random { .. } | FunctionExpr::RollingExpr { .. },
    |                                                                       ^^^^^^^^^^^ variant not found in `dsl::function_expr::FunctionExpr`
    |
   ::: /Users/nelsongriffiths/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.35.4/src/dsl/function_expr/mod.rs:107:1
    |
107 | pub enum FunctionExpr {
    | --------------------- variant `RollingExpr` not found here

For more information about this error, try `rustc --explain E0599`.
```

### Expected behavior

I expect the code to compile.

### Installed versions

<details>

pyo3-polars = {version = "0.9.0", features = ["derive"]}
polars = {version = "0.35.4", features = ["fmt", "performant", "chunked_ids", "lazy", "zip_with", "random"]}

</details>
