### ISSUE TITLE
Pyarrow can't read polars RLE_DICT encoded parquet files

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#12801]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pyarrow.parquet

n = 100_000
df = pl.DataFrame({"x": ["aaaaaa"] * n})
df.write_parquet("____test.parquet")
pyarrow.parquet.read_table("____test.parquet")
```
`OSError: Column cannot have more than one dictionary.`

### Issue description

Code works with `polars==0.19.15`, fails with `polars==0.19.17`. I assume it's the new RLE_DICT encoding.

I don't know if this is an issue in polars or pyarrow.
I'm happy to open an issue over there if needed.

### Expected behavior

I hope there's some parquet standard that everyone can follow so they can all read and write the same data...

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.5.1
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.4.0
gevent:               <not installed>
matplotlib:           3.8.1
numpy:                1.25.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             2.2.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.15
xlsx2csv:             0.8.1
xlsxwriter:           3.1.2
```

</details>

**Comment by deanm0000** [comment]
I got the same behavior. I'd argue that it's a polars issue unless/until it's established that pyarrow is the one deviating from the standard.

Here are a couple possibly helpful bits of info:

```
pq.ParquetFile("____test.parquet").metadata.row_group(0).column(0)
<pyarrow._parquet.ColumnChunkMetaData object at 0x7f4fa1a7cb80>
  file_offset: 12660
  file_path: 
  physical_type: BYTE_ARRAY
  num_values: 100000
  path_in_schema: x
  is_stats_set: False
  statistics:
    None
  compression: ZSTD
  encodings: ('PLAIN', 'RLE', 'RLE_DICTIONARY')
  has_dictionary_page: False
  dictionary_page_offset: None
  data_page_offset: 4
  total_compressed_size: 12656
  total_uncompressed_size: 12620
```

```
pq.write_table(df.to_arrow(), '__test2.parquet', write_statistics=False, compression='zstd')
pq.ParquetFile("__test2.parquet").metadata.row_group(0).column(0)
<pyarrow._parquet.ColumnChunkMetaData object at 0x7f4fa1a6e660>
  file_offset: 80
  file_path: 
  physical_type: BYTE_ARRAY
  num_values: 100000
  path_in_schema: x
  is_stats_set: False
  statistics:
    None
  compression: ZSTD
  encodings: ('PLAIN', 'RLE', 'RLE_DICTIONARY')
  has_dictionary_page: True
  dictionary_page_offset: 4
  data_page_offset: 37
  total_compressed_size: 76
  total_uncompressed_size: 58
```

The key difference seems to be `has_dictionary_page` so that's probably something that should explicitly be set rather than inferred.

[Here's](https://github.com/pola-rs/polars/issues/10956) another issue I posted a while back about polars not explicitly setting a flag according to the parquet standard. I bump that here in case there are economies of scale to address both at the same time.
