### ISSUE TITLE
read_delta & write_delta on MinIO S3 bucket

### ISSUE THREAD

**Issue by weber8thomas** [pola-rs/polars#14453]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "foo": [1, 2, 3, 4, 5],
        "bar": [6, 7, 8, 9, 10],
        "ham": ["a", "b", "c", "d", "e"],
    }
)

table_path = "s3://depictio-bucket/delta-table/"
df.write_delta(
    table_path,
    storage_options={
        "AWS_REGION": "us-east-1",
        "AWS_ACCESS_KEY_ID": "minio",
        "AWS_SECRET_ACCESS_KEY": "minio123",
    },
) 
```

Docker-compose config to setup MinIO:

```YAML
  minio:
    image: minio/minio:latest
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
```

### Log output

```shell
OSError: Generic S3 error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>minio_debug</AWSAccessKeyId><RequestId>VYE1DPQ0MZZF0A9J</RequestId><HostId>Y6CqsIAemmSlQzuqoMTjF+Go4leBwVaP0sPi5k0wD22Ze6QoW9CUVZKNp7EGziJ8Iey0XCvzO00=</HostId></Error>
```

### Issue description

I cannot write and read delta on MinIO S3 bucket following the example on the documentation. 

### Expected behavior

I'd expect to read and write delta tables on MinIO S3 buckets.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-14.3-arm64-arm-64bit
Python:               3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            0.15.1
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             1.10.10
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>
