### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by kalimalrazif** [pola-rs/polars#18267]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
```

### Log output

```shell
error[E0433]: failed to resolve: use of undeclared type `ParquetAsyncReader`
   --> /home/nomar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.42.0/src/plans/functions/count.rs:128:17
    |
128 |                 ParquetAsyncReader::from_uri(&path.to_string_lossy(), cloud_options, None).await?;
    |                 ^^^^^^^^^^^^^^^^^^ use of undeclared type `ParquetAsyncReader`
    |
help: a struct with a similar name exists
    |
128 |                 ParquetReader::from_uri(&path.to_string_lossy(), cloud_options, None).await?;
    |                 ~~~~~~~~~~~~~
help: consider importing this struct
    |
3   + use polars_io::prelude::ParquetAsyncReader;
    |
```

### Issue description

I try to run: "cargo build"

### Expected behavior

Error-free compilation process

### Installed versions

<details>

polars-core = "0.42.0"
polars-lazy = { version = "0.42.0", features = ["async", "dtype-full", "fmt", "parquet", "regex", "strings", "timezones", "tokio"] }
polars-io = { version = "0.42.0", features = ["async", "polars-parquet", "parquet"] }

</details>

**Comment by cmdlineluser** [comment]
Seems to be the same issue as https://github.com/pola-rs/polars/issues/18258

Both of these are gated by the `cloud` feature - I'm guessing this is new?

https://github.com/pola-rs/polars/blob/c88da1f6266a4f7f85d1487485e5943b84a2ac7f/crates/polars-io/src/parquet/read/reader.rs#L252-L253

**Comment by kalimalrazif** [comment]
I downgraded the version to 0.41.3 and I have the same result

```
error[E0433]: failed to resolve: use of undeclared type `ParquetAsyncReader`
   --> /home/nomar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.41.3/src/plans/functions/count.rs:125:17
    |
125 |                 ParquetAsyncReader::from_uri(&path.to_string_lossy(), cloud_options, None).await?;
    |                 ^^^^^^^^^^^^^^^^^^ use of undeclared type `ParquetAsyncReader`
    |
help: a struct with a similar name exists
    |
125 |                 ParquetReader::from_uri(&path.to_string_lossy(), cloud_options, None).await?;
    |                 ~~~~~~~~~~~~~
help: consider importing this struct
    |
3   + use polars_io::prelude::ParquetAsyncReader;
    |
```

But despite including in my Cargo.toml:

```toml
polars-core = "0.41.3"
polars-lazy = { version = "0.41.3", features = ["async", "dtype-full", "fmt", "parquet", "regex", "strings", "timezones", "tokio"] }
polars-io = { version = "0.41.3", features = ["parquet"] }
```

The building process shows this:

```
   Compiling polars-row v0.35.4
   Compiling polars-row v0.41.3
   Compiling polars-parquet v0.41.3
   Compiling polars-time v0.41.3
   Compiling polars-io v0.41.3
   Compiling polars-time v0.35.4
   Compiling polars-io v0.35.4
```

**Comment by kalimalrazif** [comment]
Hi, removing some features mi code builds again, the new Cargo.toml is like this:

```toml
polars-core = "0.41.3"
polars-lazy = { version = "0.41.3", features = ["dtype-full", "fmt", "parquet", "regex", "strings"] }
```
