### ISSUE TITLE
[rust-0.44] No way to mutate MutableStructArray

### ISSUE THREAD

**Issue by utkarshgupta137** [pola-rs/polars#19585]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

In #19123, the `mut_values()` method was removed from `MutableStructArray`. As far as I can tell, there is no way to add elements to `MutableStructArray` anymore. I've gone through all the APIs available in the [docs](https://docs.rs/polars-arrow/0.44.2/polars_arrow/array/struct.MutableStructArray.html) & also gone through the code base. The only workaround seems to be to copy the `MutableStructArray` code & re-add `mut_values`.
All other similar `MutableXYZArray` still provide one way or another (either [`mut_values()`](https://docs.rs/polars-arrow/0.44.2/polars_arrow/array/struct.MutableListArray.html#method.mut_values) or [`push()`](https://docs.rs/polars-arrow/latest/polars_arrow/array/struct.MutableBinaryArray.html#method.push)) to mutate the data. Also, there are [two](https://github.com/pola-rs/polars/blob/rs-0.44.2/crates/polars-arrow/src/io/avro/read/nested.rs#L30) [places](https://github.com/pola-rs/polars/blob/rs-0.44.2/crates/polars-parquet/src/arrow/read/statistics/struct_.rs#L30) in the code base where a similar struct is used & both of them still provide `mut_values()` method.

### Expected behavior

My personal preference would be to re-add the `mut_values()` method. If that is something the devs want to do away with, we at least need `push()` & preferably `extend()`.

### Installed versions

```toml
polars = { version = "0.44", default-features = false, features = ["bigidx", "dtype-datetime", "dtype-date", "dtype-time", "dtype-duration", "dtype-u8", "dtype-u16", "dtype-i8", "dtype-i16", "performant", "ipc", "polars-io"] }
polars-core = { version = "0.44", default-features = false }
```
