### ISSUE TITLE
Unable to enable feature parquet in Cargo.toml

### ISSUE THREAD

**Issue by GregBowyer** [pola-rs/polars#22912]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```toml
[package]
name = "fsst-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
polars = { version = "0.48.1", features = ["lazy", "parquet"] }
```

### Log output

```shell
❯ cargo check
error: failed to select a version for the requirement `zlib-rs = "^0.5.0"`
candidate versions found which didn't match: 0.4.2, 0.4.1, 0.4.0, ...
location searched: crates.io index
required by package `libz-rs-sys v0.5.0`
    ... which satisfies dependency `libz-rs-sys = "^0.5.0"` of package `flate2 v1.1.1`
    ... which satisfies dependency `flate2 = "^1"` (locked to 1.1.1) of package `polars-parquet v0.48.1`
    ... which satisfies dependency `polars-parquet = "^0.48.1"` (locked to 0.48.1) of package `polars v0.48.1`
    ... which satisfies dependency `polars = "^0.48.1"` (locked to 0.48.1) of package `fsst-test v0.1.0 (/data/user-agents/fsst-test)`
```

### Issue description

When enabling parquet as a feature, there seems to be some dep resolution issue

This is worked around by `cargo add zlib-rs` 

### Expected behavior

To resolve the deps?

### Installed versions

<details>

lazy
parquet

</details>
