### ISSUE TITLE
Upgrading rust dependency: with features: `is_in` but `polars` does not have these features

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#3366]
#### What language are you using?

Rust

#### Which feature gates did you use?

```
polars = { git = "https://github.com/pola-rs/polars", rev = "7ddff81702b9410f15f01f6106c7afd5b2f5d181", features = ["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"] }
```

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

```
polars = { git = "https://github.com/pola-rs/polars", rev = "7ddff81702b9410f15f01f6106c7afd5b2f5d181", features = ["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"] }
```

#### What operating system are you using polars on?

macOS Monterey

#### What language version are you using

```
rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```
#### Describe your bug.

Upgrading to any commit after commit `7ddff81702b9410f15f01f6106c7afd5b2f5d181` cannot be compiled with error:
```
error: failed to select a version for `polars`.
    ... required by package `<...> v0.1.0 (<...>)`
versions that meet the requirements `*` are: 2.0.0+zstd.1.5.2

the package `<...>` depends on `polars`, with features: `is_in` but `polars` does not have these features.
``` 

The commit before this commit works fine `929ec8c91912f9272611fb949e6f9cc97aeee0e4`. But any after are also failing. If removing the `is_in` feature it fails on the `json` feature instead.

Have these changed names or is this indeed a bug?

**Comment by ritchie46** [comment]
I don't know?

This `cargo.toml` compiles for me:

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { path = "../polars", features = ["is_in"] }
```
