### ISSUE TITLE
Issue with identifying column type in from_dicts() and from_dict()

### ISSUE THREAD

**Issue by s-b90** [pola-rs/polars#4015]
Python 3.10, Ubuntu 22.04, polars 0.13.52 (latest)

#### Describe your bug.

When trying to create pl.DataFrame from python dict with mixed int and float values, polars may raise an error of identifying column dtype. Even infer_schema length does not make sense.

```python
 pl.from_dict({'column': [-3, 2, 0, 4.6]})
 TypeError: 'float' object cannot be interpreted as an integer
```
or 
```python
pl.from_dicts([{'column': -3},
              {'column': 2},
              {'column': 0},
              {'column': 4.6}], infer_schema_length=1000)
ComputeError: Could not append Float64(4.6) to builder; make sure that all rows have the same schema.
Or consider increasing the the 'schema_inference_length' argument.
```

**Comment by s-b90** [comment]
Yep, it will be great to provide strict schema to builder before init. I think Null will be great for values which mismatch schema type. And maybe, as option, add argument that allow raise an error in mismatch case.
Something like that:
```python
pl.from_dicts(data, schema, infer_schema_length, errors)
```
```
parameters:
    data: Sequence[dict[str, Any]]
    schema: dict[str, pl.datatypes], default None.
    infer_schema_length: int, default 50, ignored when schema provided.
    errors: str {'raise', 'ignore'}, default 'raise'. If  'raise' and values in data mismatch schema - raise an error.
                                                      If 'ignore'  - fill mismatch values with Null.
```

And do the same for `pl.from_dict`
