### ISSUE TITLE
github actions: run action if the spec file has changed

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#4084]
This can prevent reverts on master if the spec turns out to be invalid.

**Comment by zundertj** [comment]
I think #4125 comes close, but it is not the same, because not all spec files are being monitored, and I think that is what you are intending here?

Should we define a workflow that is triggered on 
```
on: 
  push:
    paths:
      - '.github/workflows/*' 
```
and then do ?
