### ISSUE TITLE
Bad data when reading parquet files

### ISSUE THREAD

**Issue by aguillot** [pola-rs/polars#5784]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading some parquet files, data is corrupted. The row count is the same but it's just copies of the same lines.
These files were working fine on version 0.14.28.

For files with similar data, here is the pyarrow details for a working one:
```
<pyarrow._parquet.ColumnChunkMetaData object at 0x7f2449e58d10>
  file_offset: 11089610
  file_path: 
  physical_type: BYTE_ARRAY
  num_values: 4106823
  path_in_schema: hash
  is_stats_set: True
  statistics:
    <pyarrow._parquet.Statistics object at 0x7f242d09c900>
      has_min_max: True
      min: xxxx
      max: xxxx
      null_count: 0
      distinct_count: 0
      num_values: 4106823
      physical_type: BYTE_ARRAY
      logical_type: String
      converted_type (legacy): UTF8
  compression: SNAPPY
  encodings: ('RLE', 'BIT_PACKED', 'PLAIN_DICTIONARY')
  has_dictionary_page: False
  dictionary_page_offset: None
  data_page_offset: 11089610
  total_compressed_size: 6692231
  total_uncompressed_size: 6734071
```

And a failing file:
```
<pyarrow._parquet.ColumnChunkMetaData object at 0x7f6f8693f830>
  file_offset: 8244914
  file_path: 
  physical_type: BYTE_ARRAY
  num_values: 3892360
  path_in_schema: hash
  is_stats_set: True
  statistics:
    <pyarrow._parquet.Statistics object at 0x7f6f801f1030>
      has_min_max: True
      min: xxxx
      max: xxxx
      null_count: 0
      distinct_count: 0
      num_values: 3892360
      physical_type: BYTE_ARRAY
      logical_type: String
      converted_type (legacy): UTF8
  compression: SNAPPY
  encodings: ('RLE', 'BIT_PACKED', 'PLAIN', 'PLAIN_DICTIONARY', 'RLE_DICTIONARY')
  has_dictionary_page: True
  dictionary_page_offset: 8244914
  data_page_offset: 8332681
  total_compressed_size: 5167237
  total_uncompressed_size: 13282169
```

Maybe the dictionary encoding is causing the issue

### Reproducible example

```python
import polars as pl

df = pl.read_parquet("sample.parquet")
assert len(df.filter(pl.col("hash") == "f8330e0397f3cd27c02234f531e8ef1f033d177a")) == 6
```

### Expected behavior

[sample.parquet.zip](https://github.com/pola-rs/polars/files/10208497/sample.parquet.zip)

Correct values from the data, as in version 0.14.28:
```
>>> df.groupby("hash").count().sort(["count", "hash"], reverse=True)
shape: (51, 2)
┌─────────────────────────────────────┬───────┐
│ hash                                ┆ count │
│ ---                                 ┆ ---   │
│ str                                 ┆ u32   │
╞═════════════════════════════════════╪═══════╡
│ aa5a38a39e02611b54cad6874d952ce5... ┆ 8     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 30eb38139bba127cf66f136995e378ea... ┆ 8     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ f8330e0397f3cd27c02234f531e8ef1f... ┆ 6     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ f77740fd6c5c15a6a3c097a940358fe4... ┆ 5     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ ...                                 ┆ ...   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1f99526193a4d2a7fdccbc13eaed0d2f... ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1d4c65a48c13e30616425b3318406a77... ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 1b7365898ce5a933f1124e31c3f5ead7... ┆ 1     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 0d6dac1a0b91b9c0cc37d5db10d2525e... ┆ 1     │
└─────────────────────────────────────┴───────┘
```

But with version 0.15.2 and 0.15.3, all the data is a copy of an even number of lines.
2x50 for this 100 row sample.
```
>>> df.groupby("hash").count().sort(["count", "hash"], reverse=True)
shape: (2, 2)
┌─────────────────────────────────────┬───────┐
│ hash                                ┆ count │
│ ---                                 ┆ ---   │
│ str                                 ┆ u32   │
╞═════════════════════════════════════╪═══════╡
│ f8330e0397f3cd27c02234f531e8ef1f... ┆ 50    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ aa5a38a39e02611b54cad6874d952ce5... ┆ 50    │
└─────────────────────────────────────┴───────┘

```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.3
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python: 3.10.8 (main, Oct 17 2022, 08:58:13) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: <not installed>
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>
